#E-Vehicle Incentive Impact Tool
#UI
#Mike McQueen

#Load Packages
library(shiny)
library(tidyr)
library(dplyr)
library(ggplot2)
library(units)
library(measurements)
library(stringr)
library(shinydashboard)
library(shinyBS)

# Define UI for application
ui <- dashboardPage(skin = "green",
                    
  # Application header
  dashboardHeader(title = "Electric Vehicle Incentive Cost and Impact",
                  titleWidth = 450,
                  #some magic I found on the internet to add the logo to the upper right hand corner
                  tags$li(a(href = 'http://trec.pdx.edu',
                         img(src='TREC_white_horiz.png',
                             title = "TREC",
                             height = '30px'),
                         style = "padding-top:10px; padding-bottom:10px;"),
                         class = "dropdown")
                  ),
  
  #================================#
  #Sidebar####
  #================================#
  # Sidebar with a slider input for number of bins 
  dashboardSidebar(
    sidebarMenu(
                menuItem("Trips",
                         icon = icon("route"),
                             p("Car Trip Attributes"),
                             numericInput("in_Car_Trips_Daily_Avg",
                                          "Average Unique Trips per Day per Automobile",
                                          value = 5.15,
                                          step = .1),
                             bsTooltip("in_Car_Trips_Daily_Avg", "Average number of trips per automobile per day in the region",
                                          "right", options = list(container = "body")),
                             numericInput("in_Car_Trip_Avg_Length",
                                          "Average Trip Length per Day (mi)",
                                          value = 9.30,
                                          step = .1),
                             bsTooltip("in_Car_Trip_Avg_Length", "Average VMT per automobile trip in the region",
                                       "right", options = list(container = "body")),
                             selectInput("in_preset_Car_Trips_Daily_Avg",
                                         "Choose Preset:",
                                         Trips %>% pull(State),
                                         selected = "CA"),
                             bsTooltip("in_preset_Car_Trips_Daily_Avg", "These presets are sourced from the NHTS 2017",
                                       "right", options = list(container = "body")),
                             actionButton("apply_in_preset_Car_Trips_Daily_Avg",
                                          "Apply Preset"),
                             bsTooltip("apply_in_preset_Car_Trips_Daily_Avg", "Apply the preset selected above",
                                       "right", options = list(container = "body"))
                  ),
                  menuItem("Electricity",
                           icon = icon("bolt"),
                             p("Electricity Generation Attributes"),
                             numericInput("in_elec_gen_emissions",
                                          "State CO2 emissions rate for electricity generation (lb/MWh)",
                                          value = 420.4,
                                          step = 10),
                             bsTooltip("in_elec_gen_emissions", "Average CO2 emissions of electricity generation",
                                       "right", options = list(container = "body")),
                             selectInput("in_preset_elec_gen_emissions",
                                         "Choose Preset:",
                                         Electricity %>% pull(State),
                                         selected = "CA"),
                             bsTooltip("in_preset_elec_gen_emissions", "These presets are sourced from the US EPA eGrid 2018 data",
                                       "right", options = list(container = "body")),
                             actionButton("apply_in_preset_elec_gen_emissions",
                                          "Apply Preset"),
                             bsTooltip("apply_in_preset_elec_gen_emissions", "Apply the preset selected above",
                                       "right", options = list(container = "body"))
                  ),
                  menuItem("Incentives",
                           icon = icon("hand-holding-usd"),
                           p("Incentive Program Budgeting"),
                           numericInput("in_BEV_incentive",
                                          "BEV incentive ($)",
                                          value = 2000,
                                          step = 50),
                           bsTooltip("in_BEV_incentive", "Set the dollar amount of the incentive",
                                     "right", options = list(container = "body")),
                           numericInput("in_PHEV_incentive",
                                          "PHEV incentive ($)",
                                          value = 1000,
                                          step = 50),
                           bsTooltip("in_PHEV_incentive", "Set the dollar amount of the incentive",
                                     "right", options = list(container = "body")),
                           numericInput("in_FCEV_incentive",
                                          "FCEV incentive ($)",
                                          value = 4500),
                           bsTooltip("in_FCEV_incentive", "Set the dollar amount of the incentive",
                                     "right", options = list(container = "body")),
                           numericInput("in_EBike_incentive",
                                          "E-Bike incentive ($)",
                                          value = 300,
                                          step = 50),
                           bsTooltip("in_EBike_incentive", "Set the dollar amount of the incentive",
                                     "right", options = list(container = "body")),
                           numericInput("in_test_budget",
                                          "Total budget ($)",
                                          value = 3000000,
                                          step = 10000),
                           bsTooltip("in_test_budget", "Set the total budget for all incentives",
                                     "right", options = list(container = "body")),
                           sliderInput("in_BEV_per_budget",
                                            "BEV Budget Percentage Allotment",
                                            min = 0,
                                            max = 100,
                                            value = 0,
                                            step = 1),
                           bsTooltip("in_BEV_per_budget", "Set the portion of the budget allotted to this mode. The sum of all items must not exceed 100%",
                                     "right", options = list(container = "body")),
                           sliderInput("in_EBike_per_budget",
                                             "E-Bike Budget Percentage Allotment",
                                             min = 0,
                                             max = 100,
                                             value = 0,
                                             step = 1),
                           bsTooltip("in_EBike_per_budget", "Set the portion of the budget allotted to this mode. The sum of all items must not exceed 100%",
                                     "right", options = list(container = "body")),
                           sliderInput("in_PHEV_per_budget",
                                             "PHEV Budget Percentage Allotment",
                                             min = 0,
                                             max = 100,
                                             value = 0,
                                             step = 1),
                           bsTooltip("in_PHEV_per_budget", "Set the portion of the budget allotted to this mode. The sum of all items must not exceed 100%",
                                     "right", options = list(container = "body")),
                           sliderInput("in_FCEV_per_budget",
                                             "FCEV Budget Percentage Allotment",
                                             min = 0,
                                             max = 100,
                                             value = 0,
                                             step = 1),
                           bsTooltip("in_FCEV_per_budget", "Set the portion of the budget allotted to this mode. The sum of all items must not exceed 100%",
                                     "right", options = list(container = "body"))
                  ),
                  menuItem("ICE",
                           icon = icon("gas-pump"),
                             p("Internal Combustion Engine vehicles"),
                             numericInput("in_ICE_Fuel_Economy",
                                          "Average Auto Fuel Economy (mpg)",
                                          value = 25.2,
                                          step = 1),
                             bsTooltip("in_ICE_Fuel_Economy", "Average fuel economy of all existing ICE vehicle within the region",
                                       "right", options = list(container = "body")),
                             selectInput("in_preset_ICE_Fuel_Economy",
                                         "Choose Preset:",
                                         ICE %>% pull(Name),
                                         selected = "CA_Average"),
                             bsTooltip("in_preset_ICE_Fuel_Economy", "State presets are sourced from the state DOT. The US preset is sourced from the US Bureau of Transportation Statistics, 2017, for light duty vehicles.",
                                       "right", options = list(container = "body")),
                             actionButton("apply_in_preset_ICE_Fuel_Economy",
                                          "Apply Preset"),
                             bsTooltip("apply_in_preset_ICE_Fuel_Economy", "Apply the preset selected above",
                                       "right", options = list(container = "body"))
                  ),
                  menuItem("E-Bike",
                           icon = icon("bicycle"),
                             p("Electric Bicycles"),
                             checkboxInput("in_EBike_include",
                                           "Include",
                                           T),
                             bsTooltip("in_EBike_include", "Include this mode in the outputs",
                                       "right", options = list(container = "body")),
                             numericInput("in_EBike_econ",
                                           "Avg E-Bike Fuel Economy (kwh/100 mi)",
                                           value = 1.91,
                                           step = 0.1),
                             bsTooltip("in_EBike_econ", "The average fuel economy of the e-bikes that will be eligible for the incentive program. This value can be obtained from manufacturers.",
                                       "right", options = list(container = "body")),
                             numericInput("in_EBike_VMT_r",
                                          "E-Bike VMT Replacement Ratio",
                                          value = .15,
                                          step = .05),
                             bsTooltip("in_EBike_VMT_r", "Between 0 and 1. This value represents the average ratio of ICE VMT that the e-bike will replace.",
                                       "right", options = list(container = "body")),
                             selectInput("in_preset_EBike",
                                         "Choose Preset:",
                                         mix %>% filter(mix_type == "EBike") %>% pull(mix_name),
                                         selected = "VT_mix"),
                             bsTooltip("in_preset_EBike", "Presets are an average of specifications from a mix of e-bike makes and models.",
                                       "right", options = list(container = "body")),
                             selectInput("in_preset_EBike_2",
                                         "Choose Preset Efficiency Level:",
                                         c("Low", "High"),
                                         selected = "Low"),
                             bsTooltip("in_preset_EBike_2", "There is a lower limit and an upper limit of e-bike fuel economy, depending on how the e-bike is ridden. Select Low for the average lower efficiency limit and High for the average higher efficiency limit",
                                       "right", options = list(container = "body")),
                             actionButton("apply_in_preset_EBike",
                                          "Apply Preset"),
                             bsTooltip("apply_in_preset_EBike", "Apply the preset selected above",
                                       "right", options = list(container = "body"))
                  ),
                  menuItem("BEV",
                           icon = icon("charging-station"),
                             p("Battery Electric Vehicles"),
                             checkboxInput("in_BEV_include",
                                           "Include",
                                           T),
                             bsTooltip("in_BEV_include", "Include this mode in the outputs",
                                       "right", options = list(container = "body")),
                             numericInput("in_BEV_econ",
                                          "Avg EV Fuel Economy (kWh/100 mi)",
                                          value = 32.19,
                                          step = 1),
                             bsTooltip("in_BEV_econ", "The average fuel economy of the BEVs eligible for the incentive program",
                                       "right", options = list(container = "body")),
                             selectInput("in_preset_BEV",
                                         "Choose Preset:",
                                         mix %>% filter(mix_type == "BEV") %>% pull(mix_name),
                                         selected = "CA_Feb_20"),
                             bsTooltip("in_preset_BEV", "These presets are weighted averages of vehicles sold through existing vehicle incentive programs, and can be used to approximate the average fuel economy of vehicles sold under a future incentive program.",
                                       "right", options = list(container = "body")),
                             actionButton("apply_in_preset_BEV",
                                          "Apply Preset"),
                             bsTooltip("apply_in_preset_BEV", "Apply the preset selected above",
                                       "right", options = list(container = "body"))
                  ),
                  menuItem("PHEV", 
                           icon = icon("envira"),
                             p("Plug-in Hybrid Electric Vehicles"),
                             checkboxInput("in_PHEV_include",
                                           "Include",
                                           F),
                             bsTooltip("in_PHEV_include", "Include this mode in the outputs",
                                       "right", options = list(container = "body")),
                             numericInput("in_PHEV_elec_econ",
                                          "Avg E-Mode Fuel Economy (kWh/100 mi)",
                                          value = 32,
                                          step = 1),
                             bsTooltip("in_PHEV_elec_econ", "The average electric drive fuel economy of the PHEVs eligible for the incentive program. The vehicles are assumed to travel in the electric mode until they reach their maximum electric mode range for the day.",
                                       "right", options = list(container = "body")),
                             numericInput("in_PHEV_range_elec",
                                          "Avg E-Mode Range (mi)",
                                          value = 33,
                                          step = 1),
                             bsTooltip("in_PHEV_range_elec", "The average electric drive range of the PHEVs eligible for the incentive program. This is the daily limit for the number of miles that the vehicle will travel in electric drive mode.",
                                       "right", options = list(container = "body")),
                             numericInput("in_PHEV_ICE_econ",
                                          "Avg ICE Fuel Economy (mpg)",
                                          value = 44,
                                          step = 1),
                             bsTooltip("in_PHEV_ICE_econ", "The average ICE (gasoline) fuel economy of the PHEVs eligible for the incentive program. All remaining average daily miles above the electric drive range will be assumed to be travelled using the gasoline mode.",
                                       "right", options = list(container = "body")),
                             selectInput("in_preset_PHEV",
                                         "Choose Preset:",
                                         mix %>% filter(mix_type == "PHEV") %>% pull(mix_name),
                                         selected = "CA_Feb_20"),
                             bsTooltip("in_preset_PHEV", "These presets are weighted averages of vehicles sold through existing vehicle incentive programs, and can be used to approximate the average fuel economy of vehicles sold under a future incentive program.",
                                       "right", options = list(container = "body")),
                             actionButton("apply_in_preset_PHEV",
                                          "Apply Preset"),
                             bsTooltip("apply_in_preset_PHEV", "Apply the preset selected above",
                                       "right", options = list(container = "body"))
                  ),
                  menuItem("FCEV", 
                           icon = icon("atom"),
                             p("Fuel Cell Electric Vehicles"),
                             checkboxInput("in_FCEV_include",
                                           "Include",
                                           F),
                             bsTooltip("in_FCEV_include", "Include this mode in the outputs",
                                       "right", options = list(container = "body")),
                             numericInput("in_FCEV_econ",
                                          "Avg Fuel Economy (mi/kg H2)",
                                          value = 65.64,
                                          step = 1),
                             bsTooltip("in_FCEV_econ", "The average hydrogen electric drive fuel economy of the FCEVs eligible for the incentive program.",
                                       "right", options = list(container = "body")),
                             numericInput("in_renew_energy_ratio",
                                          "Ratio Electrolysis Renewable Energy",
                                          value = .10,
                                          step = .1),
                             bsTooltip("in_renew_energy_ratio", "Between 0 and 1. This tool assumes that all hydrogen used for fueling FCEVs is produced by electrolysis, which requires electricity. The amount of electricity required is multiplied by the emissions rate specified in the Electricity tab in order to calculate the net carbon emissions avoided. However, the value in this box is a ratio of the electricity required that can be assumed to be generated by 100% renewable sources (0 carbon emissions). An example of this could be an electrolyzer that has its own solar array or wind farm to generate the required electricity.",
                                       "right", options = list(container = "body")),
                             selectInput("in_preset_FCEV",
                                         "Choose Preset:",
                                         mix %>% filter(mix_type == "FCEV") %>% pull(mix_name),
                                         selected = "CA_Feb_20"),
                             bsTooltip("in_preset_FCEV", "The CA_Feb_20 preset is a weighted average of vehicles sold through existing vehicle incentive programs in CA, and can be used to approximate the average fuel economy of vehicles sold under a future incentive program. The FCEV_Equal_4 preset is a simple average of the fuel economies of the four existing fuel cell passenger vehicles sold in the US.",
                                       "right", options = list(container = "body")),
                             actionButton("apply_in_preset_FCEV",
                                          "Apply Preset"),
                             bsTooltip("apply_in_preset_FCEV", "Apply the preset selected above",
                                       "right", options = list(container = "body"))
                  ),
                  fluidRow(
                    column(width = 10, align = "center",
                           downloadButton("report", "Download report", class = "butt"),
                           tags$head(tags$style(".butt{background-color: SteelBlue;} .butt{color: white;}"))),
                    bsTooltip("report", "Generates an html output of the current tool state and graphs for printing and sharing",
                              "right", options = list(container = "body"))
                  )
    )
  ),
    #================================#
    #Main Panel####
    #================================#
    # Show a plot of the generated distribution
    dashboardBody(
      fluidRow(
        column(width = 12,
               offset = 3,
               align = "center",
               box(plotOutput("g1"),
                   bsTooltip("g1", "This plot shows the projected cost efficiency of carbon saved, that is, the cost per kg of CO2 avoided. The lines assist in comparing the cost efficiencies of different modes at the incentive values selected by the user.",
                             "right", options = list(container = "body")),
                   sliderInput("g1_x",
                               label = "X Axis Range",
                               min = 0,
                               max = 10000,
                               value = c(0, 5000),
                               step = 500),
                   sliderInput("g1_y",
                               label = "Y Axis Range",
                               min = 0,
                               max = 15,
                               value = c(0, 4),
                               step = .25))
        )
        ),
      fluidRow(
        box(plotOutput("g2"),
            bsTooltip("g2", "This plot shows the number of vehicles that could be incentivized if the entire budget was spent on one mode alone.",
                      "right", options = list(container = "body")),
            plotOutput("g4"),
            bsTooltip("g4", "This plot shows the distribution and number of vehicles that could be incentivized based on the budget allottments specified in the Incentives tab.",
                      "right", options = list(container = "body")),
            sliderInput("g2_g4_x",
                        label = "X Axis Range",
                        min = 0,
                        max = 10e6,
                        value = c(0, 5e6),
                        step = 10000),
            sliderInput("g2_g4_y",
                        label = "Y Axis Range",
                        min = 0,
                        max = 100000,
                        value = c(0, 10000),
                        step = 1000)),
        box(plotOutput("g3"),
            bsTooltip("g3", "This plot shows the total CO2 savings that could be realized if the entire budget was spent on one mode alone.",
                      "left", options = list(container = "body")),
            plotOutput("g5"),
            bsTooltip("g5", "This plot shows the distribution and total CO2 savings that could be realized based on the budget allottments specified in the Incentives tab.",
                      "left", options = list(container = "body")),
            sliderInput("g3_g5_x",
                        label = "X Axis Range",
                        min = 0,
                        max = 10e6,
                        value = c(0, 5e6),
                        step = 10000),
            sliderInput("g3_g5_y",
                        label = "Y Axis Range",
                        min = 0,
                        max = 30e6,
                        value = c(0, 15e6),
                        step = 5e5))
      )
    )
  )